# Generated by Django 5.0.6 on 2024-06-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['id'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
